export const memberList_1 = [
    {
        name:'我的账户',
        children:[
            {
                name:'个人中心',
                key:'/member',
                exact:true
            },
            {
                name:'消息通知',
                key:'/member/message'
            },
            {
                name:'安全设置',
                key:'/member/security'
            },
            {
                name:'地址管理',
                key:'/member/address',
                exact:true
            },
            {
                name:'我的积分',
                key:'/member/myPoints'
            },
            {
                name:'我的足迹',
                key:'/member/myTracks'
            },
            {
                name:'邀请有礼',
                key:'/member/politeInvitation'
            },
            {
                name:'幸运抽奖',
                key:'/member/luckyDraw'
            },
        ]
    },
]
export const memberList_2 = [
    {
        name:'交易管理',
        children:[
            {
                name:'我的订单',
                key:'/member/order',
            },
            {
                name:'优惠券',
                key:'/member/coupon'
            },
            {
                name:'礼品卡',
                key:'/member/giftCard'
            },
            {
                name:'评价晒单',
                key:'/member/evaluation'
            },
            {
                name:'售后服务',
                key:'/member/afterSale'
            }
        ]
    },
    {
        name:'我的收藏',
        children:[
            {
                name:'收藏的商品',
                key:'/member/collectibleGoods'
            },
            {
                name:'收藏的专题',
                key:'/member/collectionTopics'
            },
            {
                name:'关注的品牌',
                key:'/member/concernedBrands'
            }
        ]
    },
    {
        name:'帮助中心',
        children:[
            {
                name:'帮助中心',
                key:'/member/helpCenter'
            },
            {
                name:'在线客服',
                key:'/member/onlineService'
            }
        ]
    },
]