export const memberList_1 = [
    {
        name:'我的账户',
        children:[
            {
                name:'个人中心',
                key:'/member',
                exact:true
            },
            {
                name:'消息通知',
                key:'/xinxi'
            },
            {
                name:'安全设置',
                key:'/anquan'
            },
            {
                name:'地址管理',
                key:'/member/address',
                exact:true
            },
            {
                name:'我的积分',
                key:'/jifen'
            },
            {
                name:'我的足迹',
                key:'/zhuji'
            },
            {
                name:'邀请有礼',
                key:'/yaoqing'
            },
            {
                name:'幸运抽奖',
                key:'/xinxyun'
            },
        ]
    },
]
export const memberList_2 = [
    {
        name:'交易管理',
        children:[
            {
                name:'我的订单',
                key:'/member/order',
            },
            {
                name:'优惠券',
                key:'/youhui'
            },
            {
                name:'礼品卡',
                key:'/liping'
            },
            {
                name:'评价晒单',
                key:'/pingjia'
            },
            {
                name:'售后服务',
                key:'/fuwu'
            }
        ]
    },
    {
        name:'我的收藏',
        children:[
            {
                name:'收藏的商品',
                key:'/shouc'
            },
            {
                name:'收藏的专题',
                key:'/zhuanti'
            },
            {
                name:'关注的品牌',
                key:'/pingpai'
            }
        ]
    },
    {
        name:'帮助中心',
        children:[
            {
                name:'帮助中心',
                key:'/zhongxing'
            },
            {
                name:'在线客服',
                key:'/kefu'
            }
        ]
    },
]